### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theairbend3r** [theairbend3r/decoding-thoughts#3]
- [x] Mean and std calculation.
- [x] Update conda yaml file.
- [x] DNN model fMRI.
- [x] Extract weights from final layer
